### PR TITLE
Additional metrics

### PR DESCRIPTION
**Pull request by pb82**
## Motivation
This PR adds two new metrics:

* **keycloak_request_duration**: measures server response times per route and http method
* **keycloak_response_errors**: counts response errors (responses in the 400 and 500 range).

ping @wei-lee This could be useful for mobile metrics too.

## Why
Those are two common metrics that were missing from the SPI.

## Notes

Because the request duration is measured for every http method of every route the number of additional metrics can be very large. I've tried to reduce it as much as possible by limiting the number of buckets of the histogram and not record the status code in this kind of metric.

But if we want a smaller result, we could think about only recording the overall response time and not record it per method and route.

## How
By adding a global request and response filter. The request filter adds a timestamp to every requests. The response filter uses this timestamp to measure the time it took the server to process the request. In the response filter we record this response time and also if the request failed.

## Verification Steps

1. Build the SPI from this branch and start Keycloak with it.
1. Open the metrics endpoint in a browser. You should see the new keycloak_request_duration metric. To actually see values for the keycloak_response_errors you wouls have to trigger a server error.

## Checklist:

- [x] Code has been tested locally by PR requester
- [ ] Changes have been successfully verified by another team member 

## Progress

- [x] Finished task

### CODE REVIEW

**Comment by aliok** [comment]
Code looks good. Verifying now

**Comment by aliok** [comment]
@psturc 
I keep getting this when I try to provision the APB:
{code}
+ [[ provision --extra-vars {"ADMIN_PASSWORD":"admin","ADMIN_USERNAME":"admin","USE_SHARED_SERVICE":false,"_apb_last_requesting_user":"user1","_apb_plan_id":"default","_apb_service_class_id":"2a95762e6dd54350f119910b9088e4a4","_apb_service_instance_id":"24d68abf-39bc-11e9-b162-0a580a010007","cluster":"openshift","namespace":"yyy"} == *\s\2\i\/\a\s\s\e\m\b\l\e* ]]
--
{code}

Any ideas?

**Comment by psturc** [comment]
@aliok I think it may have something to do with [this change](https://github.com/aerogearcatalog/keycloak-apb/blame/master/Dockerfile#L44), but I was testing it locally and latest keycloak-apb image from aerogearcatalog org works on community cluster...
Could you send me a link to your keycloak-apb image?

**Comment by aliok** [comment]
@psturc https://hub.docker.com/r/aliok/keycloak-alifeb2603-apb

```
      - type: dockerhub
        name: aliok
        org: aliok
        tag: latest
        white_list:
          - ".*-apb$"
```

APB desc shown in catalog: `Identity Management - Identity and Access Management aliok feb2603`

**Comment by psturc** [comment]
👀

**Comment by psturc** [comment]
@pb82 When I try to build it with `./gradlew jar` it works fine, but it does not work with 3.4.3.final keycloak version, which was used to build for keycloak-apb [here](https://github.com/aerogearcatalog/keycloak-apb/pull/122#issue-255373577)
```
➜  keycloak-metrics-spi git:(additional-metrics) ./gradlew -PkeycloakVersion="3.4.3.Final" jar

> Task :compileJava FAILED
/Users/psturc/work/aerogear/keycloak-metrics-spi/src/main/java/org/jboss/aerogear/keycloak/metrics/PrometheusExporter.java:3: error: package com.openshift.internal.restclient.model does not exist
import com.openshift.internal.restclient.model.BuildConfig;
                                              ^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.
```
cc @grdryn ^

**Comment by pb82** [comment]
@psturc Fixed. It should work fine with 3.4.3.Final now.

**Comment by grdryn** [comment]
For the keycloak APB that we build, there's a chance that we'll be updating to 4.8.3.Final soon also (just pointing that out since you're talking about the versions).

**Comment by pb82** [comment]
thanks @psturc and @aliok
