### ISSUE TITLE
KC 16.1.0 incompatibility

### ISSUE THREAD

**Issue by kostiapl** [aerogear/keycloak-metrics-spi#126]
## Description
SPI doesn't work with KC 16.1.0

## Actual Behavior

KC 16.1.0 can't run
We encountered the following exception

"processId":1056,"stackTrace":": java.lang.NoSuchMethodError: 
'org.jboss.resteasy.core.interception.ContainerRequestFilterRegistry org.jboss.resteasy.spi.ResteasyProviderFactory.getContainerRequestFilterRegistry()
'\n\tat deployment.raiffeisen-keycloak-metrics.jar//org.jboss.aerogear.keycloak.metrics.MetricsEndpointFactory.init(MetricsEndpointFactory.java:19)\n\tat 
org.keycloak.keycloak-services@16.1.0//org.keycloak.services.DefaultKeycloakSessionFactory.loadFactories(DefaultKeycloakSessionFactory.java:297)\n\t
.....

when tried to deploy KC 16.1.0 with this spi

## Environment

jboss/keycloak:16.1.0 image,  k8s environment

**Comment by kostiapl** [comment]
This was solved in 2.5.3
